/**:
  ros__parameters:
    mass: 1.53
    trajectory_control:
      antiwindup_cte: 1.0
      alpha: 0.1
      kp:
        x: 3.5
        y: 3.5
        z: 4.0
      ki:
        x: 0.015
        y: 0.015
        z: 0.05
      kd:
        x: 2.5
        y: 2.5
        z: 5.0
      roll_control:
        kp: 3.0
      pitch_control:
        kp: 3.0
      yaw_control:
        kp: 2.15

# /**:
#   ros__parameters:
#     mass: 1.53
#     trajectory_control:
#       antiwindup_cte: 1.0
#       alpha: 0.1
#       kp:
#         x: 3.5
#         y: 3.5
#         z: 4.0
#       ki:
#         x: 0.065
#         y: 0.065
#         z: 0.15
#       kd:
#         x: 2.5
#         y: 2.5
#         z: 5.0
#       roll_control:
#         kp: 4.5
#       pitch_control:
#         kp: 4.5
#       yaw_control:
#         kp: 4.0