world_name: "empty"
origin: 
    latitude: 40.4405287
    longitude: -3.6898277
    altitude: 100.0
drones:
  - model_type: "quadrotor_base"
    model_name: "drone0"
    flight_time: 60
    xyz:
      - 0.0
      - 0.0
      - 0.3
    enable_acro_control: true
    enable_velocity_control: false
    # payload:
    #   - model_type: "air_pressure"
    #     model_name: "presion"  
    #   - model_type: "magnetometer"
    #     model_name: "magnetostero"
    #   - model_type: "gps"
    #     model_name: "gepese"
    #   - model_type: "gimbal_speed"
    #     model_name: "gimbal"
    #     payload:
    #       model_type: "hd_camera"
    #       model_name: "camera"
